CREATE OR REPLACE VIEW city_metrics_travel_cost AS
SELECT
city_metrics_cost_factor_vmt.year
city_metrics_cost_factor_vmt.gallons_gasoline
city_metrics_cost_factor_vmt.cost_per_gallons_gasoline
city_metrics_cost_factor_vmt.gallons_ethanol
city_metrics_cost_factor_vmt.cost_per_gallons_ethanol
city_metrics_cost_factor_vmt.gallons_diesel
city_metrics_cost_factor_vmt.cost_per_gallons_diesel
city_metrics_cost_factor_vmt.gallons_biodiesel
city_metrics_cost_factor_vmt.cost_per_gallons_biodiesel

FROM city_metrics_cost_factor_vmt
