CREATE OR REPLACE VIEW city_metrics_other_type3 AS
SELECT

city_metrics_other_energy.city_id
city_metrics_other_energy.year
city_metrics_other_energy.other_fuel_type3,
city_metrics_other_energy.other_fuel_amount3
