CREATE OR REPLACE VIEW city_metrics_other_type4 AS
SELECT

city_metrics_other_energy.city_id
city_metrics_other_energy.year
city_metrics_other_energy.other_fuel_type4,
city_metrics_other_energy.other_fuel_amount4
