CREATE TABLE city_metrics_cost (
    id integer NOT NULL,
    city_id integer NOT NULL,
    year character varying(4) NOT NULL,
    energy_associated_costs numeric(16,4) NOT NULL,
    water_associated_costs numeric(16,4) NOT NULL,
    travel_associated_costs numeric(16,4) NOT NULL,
    waste_associated_costs numeric(16,4) NOT NULL,
    wn_energy_associated_costs numeric(16,4) NOT NULL,
    energy_type_electricity numeric(16,4) NOT NULL,
    energy_type_natural_gas numeric(16,4) NOT NULL,
    energy_type_other numeric(16,4) NOT NULL,
    wn_energy_type_electricity numeric(16,4) NOT NULL,
    wn_energy_type_natural_gas numeric(16,4) NOT NULL,
    wn_energy_type_other numeric(16,4) NOT NULL,
    energy_use_residential numeric(16,4) NOT NULL,
    energy_use_com_ind numeric(16,4) NOT NULL,
    wn_energy_use_residential numeric(16,4) NOT NULL,
    wn_energy_use_com_ind numeric(16,4) NOT NULL,
    water_use_residential numeric(16,4) NOT NULL,
    water_use_com_ind numeric(16,4) NOT NULL,
    waste_method_recycled numeric(16,4) NOT NULL,
    waste_method_landfilled numeric(16,4) NOT NULL,
    waste_method_incinerated numeric(16,4) NOT NULL
);
